services:
  consul:
    image: hashicorp/consul
    container_name: consul
    ports:
      - 8500:8500
      - 8600:8600/udp
    volumes:
      - ./data:/consul/data
      - ./config:/consul/config
    command:
      [
        'agent',
        '-server',
        '-ui',
        '-client=0.0.0.0',
        '-bootstrap-expect=1',
        '-data-dir=/consul/data',
        '-config-dir=/consul/config',
      ]
    environment:
      - CONSUL_BIND_INTERFACE=eth0
